name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Deploy only when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Zip files
      run: zip -r application.zip .

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: "ap-southeast-1"  # Update with your region
      run: |
        aws elasticbeanstalk create-application-version --application-name "devops-final-try" --version-label "${{ github.sha }}" --source-bundle S3Bucket="awsdevops-proj1",S3Key="application.zip"
        aws elasticbeanstalk update-environment --application-name "devops-final-try" --environment-name "Devops-final-try-env" --version-label "${{ github.sha }}"